/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Telas;

/**
 *
 * @author eduardo.3946
 */
public class TelaEspacoCatequisando extends javax.swing.JFrame {

    /**
     * Creates new form TelaEspacoCatequisando
     */
    public TelaEspacoCatequisando() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fabio", "C", "C", "C", "F", "C"},
                {"Algusto", "C", "F", "C", "F", "C"},
                {"Isabela", "F", "C", "F", "C", "C"},
                {"Sofia", "C", "F", "C", "C", "C"},
                {"Alice", "C", "C", "C", "F", "C"},
                {"Tamires", "F", "C", "C", "F", "C"},
                {"Franciely", "C", "C", "F", "C", "C"},
                {"Helena", "F", "C", "C", "C", "C"},
                {"hevyllyn", "C", "F", "F", "C", "C"},
                {"Luana", "F", "C", "C", "C", "C"},
                {"Emanuel", "F", "C", "C", "C", "C"}
            },
            new String [] {
                "Nome catequisando", "1", "2", "3", "4", "5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("CHAMADA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR", "1°VOLUME", "2°VOLUME", "3°VOLUME", "4°VOLUME", "5°VOLUME", "6°INADMI" }));

        jButton1.setText("Buscar");

        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Fabio", "1", "1°", "TIAGO", "FIBELY", "(44)4453", "(44)0587", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Sofia", "4", "3°", "AFDSAF", "AD", "&&&&&&&&&&&&", "(44)2545", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Alice", "5", "4°", "ASFD", "FAS", "(44)6895", "(44)2352", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Tamires", "6", "3°", "AFSD", "AF", "(44)4876", "(44)5345", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Franciely", "7", "2°", "AFD", "ASF", "(44)5687", "(44)3543", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Helena", "8", "2°AFD", "A", "FS", "(44)4573", "(44)6786", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"hevyllyn", "9", "3°", "ASFDFD", "ASF", "(44)2358", "(44)7537", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Luana", "10", "4°", "AF", "AFDA", "(44)7907", "(44)7527", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Emanuel", "11", "4°", "SF", "S", "(44)6007", "(44)7545", "OLIVEIRA", "GIRAFALESGUIMARAENS", "123", "12345678"},
                {"Algusto", "2", "1°", "", "", "", "", "", "", "", ""},
                {"Isabela", "3", "1°", "", "", "", "", "", "", "", ""}
            },
            new String [] {
                "CATEQUISANDO", "ID", "VOLUME", "PAI", "MAE", "TELEFONE PAI", "TELEFONE MAE", "JARDIM", "RUA", "NUM.RESIDENCIAL", "CEP"
            }
        ));
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(10).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TelaInicial tela = new TelaInicial();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEspacoCatequisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEspacoCatequisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEspacoCatequisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEspacoCatequisando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEspacoCatequisando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
